enhavo_app:
  menu:
    shop_catalog:
      type: shop_catalog
    shop_sales:
      type: shop_sales
    shop_configuration:
      type: shop_configuration
    shop_promotion:
      type: shop_promotion