subtrees:
    PaymentBundle:
        url: 'git@github.com:enhavo/EnhavoPaymentBundle.git'
        prefix: src/Enhavo/Bundle/PaymentBundle
        package: enhavo/payment-bundle
    ShopBundle:
        url: 'git@github.com:enhavo/EnhavoShopBundle.git'
        prefix: src/Enhavo/Bundle/ShopBundle
        package: enhavo/shop-bundle
    SyliusBridgeBundle:
        url: 'git@github.com:enhavo/EnhavoSyliusBridgeBundle.git'
        prefix: src/Enhavo/Bundle/SyliusBridgeBundle
        package: enhavo/sylius-bridge-bundle

    payment-assets:
        url: 'git@github.com:enhavo/api-payment'
        prefix: 'packages/payment'
        package: '@enhavo/payment'
    shop-assets:
        url: 'git@github.com:enhavo/shop-assets'
        prefix: 'packages/shop'
        package: '@enhavo/shop'
