services:
    Enhavo\Bundle\PaymentBundle\Action\CreatePaymentMethodActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\Form\Type\PaymentMethodCreateType:
        arguments:
            - '@Enhavo\Bundle\PaymentBundle\Provider\PaymentMethodTypeProvider'
            - '@translator'
        tags:
            - { name: form.type }

    Enhavo\Bundle\PaymentBundle\Form\Type\PaymentMethodType:
        arguments:
            - '@Enhavo\Bundle\PaymentBundle\Provider\PaymentMethodTypeProvider'
        tags:
            - { name: form.type }

    Enhavo\Bundle\PaymentBundle\Form\Type\CurrencyChoiceType:
        arguments:
            - '%enhavo_payment.currencies%'
        tags:
            - { name: form.type }

    Enhavo\Bundle\PaymentBundle\Menu\PaymentMethodMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\PaymentBundle\Menu\PaymentMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\PaymentBundle\Resolver\DefaultPaymentMethodResolver:
        arguments:
            - '@sylius.repository.payment_method'

    Enhavo\Bundle\PaymentBundle\Provider\PaymentMethodTypeProvider:
        arguments:
            - '%enhavo_payment.payment.methods%'

    sylius.form.payment:
        class: '%sylius.form.payment.class%'
        arguments:
            - '%sylius.model.payment.class%'
        tags:
            - { name: form.type }

    sylius.factory.payment_method:
        class: '%sylius.factory.payment_method.class%'
        public: true
        arguments:
            - '%sylius.model.payment_method.class%'
            - '@Enhavo\Bundle\PaymentBundle\Provider\PaymentMethodTypeProvider'
            - '@enhavo_payment.factory.gateway_config'

    enhavo_payment.form.gateway_config:
        class: '%enhavo_payment.form.gateway_config.class%'
        arguments:
            - '%enhavo_payment.model.gateway_config.class%'
            - []
            - '@Enhavo\Bundle\PaymentBundle\Provider\PaymentMethodTypeProvider'
        tags:
            - { name: form.type }

    sylius.factory.payment:
        class: '%sylius.factory.payment.class%'
        public: true
        arguments:
            - '%sylius.model.payment.class%'
            - '@enhavo_app.util.secure_url_token_generator'

    Enhavo\Bundle\PaymentBundle\Action\CompleteActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\Action\PayActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\Action\RefreshStateActionType:
        arguments:
            - '@request_stack'
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\Action\ResetActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\Action\CancelActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\PaymentBundle\EventListener\PaymentSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    enhavo_payment.manager.payment:
        alias: Enhavo\Bundle\PaymentBundle\Manager\PaymentManager
        public: true

    Enhavo\Bundle\PaymentBundle\Manager\PaymentManager:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@payum'

    enhavo_payment.resolver.payment_state_resolver:
        public: true
        alias: 'Enhavo\Bundle\PaymentBundle\Resolver\PaymentStateResolver'

    Enhavo\Bundle\PaymentBundle\Resolver\PaymentStateResolver:
        arguments:
            - '@Enhavo\Bundle\ResourceBundle\Resource\ResourceManager'

#    Enhavo\Bundle\PaymentBundle\View\PaymentDoneViewType:
#        arguments:
#            - '@sylius.repository.payment'
#            - '@enhavo_payment.resolver.payment_subject'
#        tags:
#            - { name: enhavo_app.view }

    Enhavo\Bundle\PaymentBundle\Resolver\PaymentSubjectResolver:

    enhavo_payment.resolver.payment_subject:
        alias: Enhavo\Bundle\PaymentBundle\Resolver\PaymentSubjectResolver