services:
    Enhavo\Bundle\ShopBundle\Menu\CatalogMenuType:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ConfigurationMenuType:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\SalesMenuType:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ProductMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\OrderMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ProductOptionMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\PromotionMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ProductAttributeMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ProductAssociationTypeMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\TaxCategoryMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\TaxRateMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\VoucherMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\CategoryMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\TagMenuType:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\CountryMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ShippingMethodMenu:
        tags:
            - { name: enhavo_app.menu }

    Enhavo\Bundle\ShopBundle\Menu\ShipmentMenu:
        tags:
            - { name: enhavo_app.menu }
