services:
    Enhavo\Bundle\ShopBundle\Context\SessionCartContext:
        arguments:
            - '@request_stack'
            - 'enhavo_shop_cart'
            - '@sylius.repository.order'
            - '@sylius.factory.order'
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
        tags:
            - { name: sylius.context.cart, priority: -777 }

    Enhavo\Bundle\ShopBundle\Manager\TaxationManager:

    Enhavo\Bundle\ShopBundle\Manager\PricingManager:

    Enhavo\Bundle\ShopBundle\Manager\OrderManager:
        arguments:
            - '@Enhavo\Bundle\ShopBundle\Address\AddressProviderInterface'
            - '@enhavo_app.util.secure_url_token_generator'
            - '@Enhavo\Bundle\AppBundle\Mailer\MailerManager'
            - '@sylius.order_processing.order_processor'
            - '@doctrine.orm.entity_manager'

    enhavo_shop.order_manager:
        public: true
        alias: Enhavo\Bundle\ShopBundle\Manager\OrderManager

    Enhavo\Bundle\ShopBundle\Pricing\DefaultPriceCalculator:
        arguments:
            - '@sylius.tax_calculator'
            - '@sylius.tax_rate_resolver'
        tags:
            - { name: enhavo_shop.price_calculator, priority: 10 }

    Enhavo\Bundle\ShopBundle\Pricing\PriceCalculatorInterface:
        alias: Enhavo\Bundle\ShopBundle\Pricing\DefaultPriceCalculator

    Enhavo\Bundle\ShopBundle\Taxation\Applicator\OrderShipmentTaxesApplicator:
        arguments:
            - '@sylius.factory.adjustment'
            - '@Enhavo\Bundle\ShopBundle\Shipping\DelegatingCalculator'
        tags:
            - { name: enhavo_shop.order_taxes_applicator, priority: 20 }

    Enhavo\Bundle\ShopBundle\Taxation\Applicator\OrderItemsTaxesApplicator:
        arguments:
            - '@sylius.tax_calculator'
            - '@sylius.factory.adjustment'
            - '@sylius.tax_rate_resolver'
        tags:
            - { name: enhavo_shop.order_taxes_applicator, priority: 10 }

    Enhavo\Bundle\ShopBundle\Action\BillingActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\PackingSlipActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\CancelActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\CouponActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\PaidActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\RefundActionType:
        tags:
            - { name: enhavo_resource.action }

    Enhavo\Bundle\ShopBundle\Action\ShipActionType:
        tags:
            - { name: enhavo_resource.action }

    enhavo.state_resolver.order:
        public: true
        alias: Enhavo\Bundle\ShopBundle\StateResolver\OrderStateResolver

    Enhavo\Bundle\ShopBundle\StateResolver\OrderStateResolver:
        arguments:
            - '@sm.factory'

    Enhavo\Bundle\ShopBundle\EventListener\OrderSubscriber:
        arguments:
            - '@router'
        tags:
            - { name: kernel.event_subscriber }
